Vagrant::Config.run do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "Ubuntu-11.04"

  # The url from where the 'config.vm.box' box will be fetched if it
  # doesn't already exist on the user's system.
  config.vm.box_url = "http://designdisclosure.s3.amazonaws.com/Ubuntu-11.04.box"

  # Boot with a GUI so you can see the screen. (Default is headless)
  # config.vm.boot_mode = :gui

  # Assign this VM to a host only network IP, allowing you to access it
  # via the IP. You'll need to add this to your hosts file with the domain
  config.vm.network "192.168.10.55"

  # Set the name of the box (as it will appear in VirtualBox) and RAM
  config.vm.customize do |vm|
    vm.memory_size = 512
    vm.name = "WiredMoon"
    vm.cpu_count = 1
  end

  # Share your ~/Sites folder with the VM via NFS
  config.vm.share_folder("Sites" , "/mnt/Sites", "#{ENV['HOME']}/Sites", :nfs => true)

end
